import { fetchJSON } from './apiClient'

export type LocationType = 'zone' | 'rack' | 'shelf' | 'bin'
export type LocationTypeEnum = 'RACK' | 'FLOOR'

export type Location = {
  id: string
  code: string
  name: string
  type: LocationType
  location_type?: LocationTypeEnum | null
  sector?: string | null
  level_no?: number | null
  row_no?: number | null
  pallet_no?: number | null
  parent_id?: string | null
  is_active: boolean
  created_at?: string | null
}

/** Create location: code is generated by backend from type + sector + level_no/row_no (RACK) or pallet_no (FLOOR). */
export type LocationCreateInput = {
  location_type: LocationTypeEnum
  sector: string
  level_no?: number
  row_no?: number
  pallet_no?: number
  is_active?: boolean
}

export type LocationUpdateInput = {
  sector?: string
  level_no?: number
  row_no?: number
  pallet_no?: number
  is_active?: boolean
}

export async function getLocations(includeInactive = false) {
  return fetchJSON<Location[]>('/api/v1/locations', {
    query: { include_inactive: includeInactive },
  })
}

export async function getLocation(id: string) {
  return fetchJSON<Location>(`/api/v1/locations/${id}`)
}

export async function createLocation(payload: LocationCreateInput) {
  return fetchJSON<Location>('/api/v1/locations', { method: 'POST', body: payload })
}

export async function updateLocation(id: string, payload: LocationUpdateInput) {
  return fetchJSON<Location>(`/api/v1/locations/${id}`, { method: 'PUT', body: payload })
}

export async function deactivateLocation(id: string) {
  return fetchJSON<Location>(`/api/v1/locations/${id}`, { method: 'DELETE' })
}
