import { fetchJSON } from './apiClient'

export type LocationType = 'zone' | 'rack' | 'shelf' | 'bin' | 'showroom_rack'
export type LocationTypeEnum = 'RACK' | 'FLOOR' | 'SHOWROOM_RACK'

/** Zone: NORMAL (default), EXPIRED, DAMAGED, QUARANTINE. FEFO/picking only from NORMAL. */
export type ZoneType = 'NORMAL' | 'EXPIRED' | 'DAMAGED' | 'QUARANTINE'

export type ExpiredZoneLabels = {
  label_for_slot_a: number | null
  label_for_slot_b: number | null
  updated_at?: string | null
}

export type Location = {
  id: string
  code: string
  /** Same as code; used for barcode (Code128). */
  barcode_value?: string
  name: string
  type: LocationType
  location_type?: LocationTypeEnum | null
  /** Zona turi: FEFO va terish faqat NORMAL dan. */
  zone_type?: ZoneType | string
  /** EXPIRED zona ichida barqaror slot: A yoki B. */
  expired_slot?: string | null
  /** Global sozlamadagi ko‘rsatkich (A/B uchun qo‘lda yangilanadi). */
  expired_display_label?: number | null
  sector?: string | null
  level_no?: number | null
  row_no?: number | null
  pallet_no?: number | null
  parent_id?: string | null
  warehouse_id?: string | null
  is_active: boolean
  /** Terish ketma-ketligi (yo'nalish optimizatsiyasi). */
  pick_sequence?: number | null
  created_at?: string | null
}

/** Create location: code is generated by backend from type + sector + level_no/row_no (RACK), pallet_no (FLOOR), or level_no only (SHOWROOM_RACK). */
export type LocationCreateInput = {
  location_type: LocationTypeEnum
  sector: string
  level_no?: number
  row_no?: number
  pallet_no?: number
  is_active?: boolean
  warehouse_id?: string | null
}

export type LocationUpdateInput = {
  sector?: string
  level_no?: number
  row_no?: number
  pallet_no?: number
  is_active?: boolean
  pick_sequence?: number | null
  zone_type?: ZoneType | string
  expired_slot?: string | null
}

export type WarehouseFilter = 'main' | 'showroom'

export async function getLocations(includeInactive = false, warehouse?: WarehouseFilter) {
  return fetchJSON<Location[]>('/api/v1/locations', {
    query: {
      include_inactive: includeInactive,
      ...(warehouse ? { warehouse } : {}),
    },
  })
}

export async function getLocation(id: string) {
  return fetchJSON<Location>(`/api/v1/locations/${id}`)
}

export async function createLocation(payload: LocationCreateInput) {
  return fetchJSON<Location>('/api/v1/locations', { method: 'POST', body: payload })
}

export async function updateLocation(id: string, payload: LocationUpdateInput) {
  return fetchJSON<Location>(`/api/v1/locations/${id}`, { method: 'PUT', body: payload })
}

export async function deactivateLocation(id: string) {
  return fetchJSON<Location>(`/api/v1/locations/${id}`, { method: 'DELETE' })
}

export async function getExpiredDisplayLabels() {
  return fetchJSON<ExpiredZoneLabels>('/api/v1/locations/expired-display-labels')
}

export async function patchExpiredDisplayLabels(payload: { label_for_slot_a: number; label_for_slot_b: number }) {
  return fetchJSON<ExpiredZoneLabels>('/api/v1/locations/expired-display-labels', {
    method: 'PATCH',
    body: payload,
  })
}
