PERMISSIONS: set[str] = {
    "admin:access",
    "users:manage",
    "roles:manage",
    "audit:read",
    "reports:read",
    "products:read",
    "products:write",
    "orders:read",
    "orders:sync",
    "orders:send_to_picking",
    "picking:assign",
    "documents:read",
    "documents:create",
    "documents:edit_status",
    "receiving:read",
    "receiving:write",
    "picking:read",
    "picking:pick",
    "picking:complete",
    "picking:exception",
    "inventory:read",
    "inventory:count",
    "inventory:adjust",
    "locations:manage",
    "movements:read",
    "brands:manage",
}

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "warehouse_admin": [
        "admin:access",
        "users:manage",
        "roles:manage",
        "products:read",
        "products:write",
        "orders:read",
        "orders:sync",
        "orders:send_to_picking",
        "picking:assign",
        "documents:read",
        "documents:create",
        "documents:edit_status",
        "receiving:read",
        "receiving:write",
        "picking:read",
        "picking:pick",
        "picking:complete",
        "picking:exception",
        "inventory:read",
        "inventory:count",
        "inventory:adjust",
        "locations:manage",
        "movements:read",
        "brands:manage",
        "reports:read",
        "audit:read",
    ],
    "supervisor": [
        "admin:access",
        "products:read",
        "products:write",
        "orders:read",
        "orders:sync",
        "orders:send_to_picking",
        "picking:assign",
        "documents:read",
        "documents:edit_status",
        "receiving:read",
        "receiving:write",
        "picking:read",
        "picking:pick",
        "picking:complete",
        "picking:exception",
        "inventory:read",
        "inventory:count",
        "reports:read",
        "locations:manage",
        "movements:read",
        "brands:manage",
    ],
    "picker": [
        "picking:read",
        "picking:pick",
        "picking:complete",
        "picking:exception",
    ],
    "receiver": [
        "admin:access",
        "receiving:read",
        "receiving:write",
        "documents:read",
        "products:read",
    ],
    "inventory_controller": [
        "admin:access",
        "documents:read",
        "products:read",
        "picking:read",
        "inventory:read",
    ],
}


def get_permissions_for_role(role: str) -> list[str]:
    return ROLE_PERMISSIONS.get(role, [])
