// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJBleBPQdBtVaTlf4fdse0e3EbctQTrIo',
    appId: '1:270662903150:web:b4e09affc679ec3ec60d7f',
    messagingSenderId: '270662903150',
    projectId: 'fb-warehouse-76a0c',
    authDomain: 'fb-warehouse-76a0c.firebaseapp.com',
    storageBucket: 'fb-warehouse-76a0c.firebasestorage.app',
    measurementId: 'G-TVMKRYVJPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQIzjski4DIy0PPSvTkrBYq00CigHPfH4',
    appId: '1:270662903150:android:94344eadd33f61cbc60d7f',
    messagingSenderId: '270662903150',
    projectId: 'fb-warehouse-76a0c',
    storageBucket: 'fb-warehouse-76a0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1f2zFxuX4CgIxZ1JlGRUWzv_gx_rW3U',
    appId: '1:270662903150:ios:a6cfcd7a9b059335c60d7f',
    messagingSenderId: '270662903150',
    projectId: 'fb-warehouse-76a0c',
    storageBucket: 'fb-warehouse-76a0c.firebasestorage.app',
    iosBundleId: 'uz.fbwarehouse.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1f2zFxuX4CgIxZ1JlGRUWzv_gx_rW3U',
    appId: '1:270662903150:ios:2d86ff6048799b17c60d7f',
    messagingSenderId: '270662903150',
    projectId: 'fb-warehouse-76a0c',
    storageBucket: 'fb-warehouse-76a0c.firebasestorage.app',
    iosBundleId: 'com.example.mobileFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJBleBPQdBtVaTlf4fdse0e3EbctQTrIo',
    appId: '1:270662903150:web:b21b47848bbe5420c60d7f',
    messagingSenderId: '270662903150',
    projectId: 'fb-warehouse-76a0c',
    authDomain: 'fb-warehouse-76a0c.firebaseapp.com',
    storageBucket: 'fb-warehouse-76a0c.firebasestorage.app',
    measurementId: 'G-H2M05KBP4D',
  );

}